#!/usr/bin/env bash
set -eo pipefail

export DINGO_ROOT=${DOKKU_ROOT:="/home/dingo"}
export DINGO_LIB=${DINGO_LIB:="/var/lib/dingo"}


function pluginhook {
    for script in $(ls -d ${DINGO_LIB}/plugins/*/$1); do
        $script
    done
}


function plugincommand {
    # plugin command like `foo:bar`
    cmd=(${1//:/ })
    subcmd=$(echo "$@" | sed -r "s/^${cmd[0]}://")
    script=${DINGO_LIB}/plugins/${cmd[0]}/commands
    if [ -f $script ]; then
        $script ${subcmd}
    fi
}


if [[ $(id -un) != "dingo" && $1 != "plugins-install" ]]; then
    sudo -u dingo -H $0 "$@"
    exit
fi


case "$1" in

    plugins-install)
        pluginhook install
        ;;

    *:*)
        plugincommand "$@"
        ;;

    *)
        ;;
esac
