#!/usr/bin/env bash
set -eo pipefail; [[ $DINGO_TRACE ]] && set -x

if [ -f "/etc/supervisor/conf.d/dingo.conf" ]; then
    exit
fi

# supervisor
apt-get install -y supervisor

PASSWORD=$(date | md5sum)
PASSWORD=${PASSWORD// /}
SUPERVISORD_ROOT=$DINGO_ROOT/.supervisord
mkdir -p $SUPERVISORD_ROOT
chown -R dingo $SUPERVISORD_ROOT

cat > /etc/supervisor/conf.d/dingo.conf <<EOF
[include]
files = $DINGO_ROOT/*/supervisord.conf
EOF
