#!/usr/bin/env bash
set -eo pipefail; [[ $DINGO_TRACE ]] && set -x

GITUSER=${GITUSER:-git}
GITHOME="/home/${GITUSER}"

useradd -d $GITHOME $GITUSER || true
mkdir -p $GITHOME/.ssh
touch $GITHOME/.ssh/authorized_keys

if ! grep -q git-without-password "/etc/sudoers"; then
    touch /etc/sudoers.tmp
    cp /etc/sudoers /tmp/sudoers.new
    echo "git ALL=(dingo) NOPASSWD: /usr/local/bin/dingo # git-without-password" >> /tmp/sudoers.new
    EDITOR="cp /tmp/sudoers.new" visudo
    rm /tmp/sudoers.new
fi

chown -R $GITUSER $GITHOME
