#!/usr/bin/env bash
set -eo pipefail; [[ $DINGO_TRACE ]] && set -x

add-apt-repository -y ppa:nginx/stable
apt-get update
apt-get install -y nginx

echo "include $DINGO_ROOT/nginx/*.conf;" > /etc/nginx/conf.d/dingo.conf

sed -i 's/# server_names_hash_bucket_size/server_names_hash_bucket_size/' /etc/nginx/nginx.conf

echo "$DINGO_HOSTNAME" > $DINGO_ROOT/HOSTNAME

/etc/init.d/nginx start
