#!/usr/bin/env bash

set -eo pipefail; [[ $DINGO_TRACE ]] && set -x

APP=$1
BUILD_ROOT=${BUILD_ROOT:="$DINGO_ROOT/$APP/build"}

# detect if this is Python project
if [[ ! -f $BUILD_ROOT/requirements.txt && ! -f $BUILD_ROOT/setup.py ]]; then
    exit 1
fi

RUNTIME_ROOT=${DINGO_ROOT}/$APP/runtime

if [ -d $RUNTIME_ROOT ]; then
    if [ -f $BUILD_ROOT/requirements.txt ]; then
        echo "Install requirements"
        $RUNTIME_ROOT/bin/pip install -q -r "$BUILD_ROOT/requirements.txt"
    fi
fi

# record PATH
dingo config:set $APP PATH=$PATH
