#!/usr/bin/env bash
set -eo pipefail; [[ $DINGO_TRACE ]] && set -x

curl -kL https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py | python
rm setuptools-*.tar.gz
easy_install -U pip

# virtualenv
pip install -U virtualenv
