#!/usr/bin/env bash

set -eo pipefail; [[ $DINGO_TRACE ]] && set -x

APP=$1
BUILD_ROOT=${BUILD_ROOT:="$DINGO_ROOT/$APP/build"}

# detect if this is Python project
if [[ ! -f $BUILD_ROOT/requirements.txt && ! -f $BUILD_ROOT/setup.py ]]; then
    exit 1
fi

#: TODO use pyenv

# PYTHON_RUNTIME='default'
virtualenv ${DINGO_ROOT}/$APP/runtime
